### ISSUE TITLE
Problem with PCF when added twice (not reproductible every time)

### ISSUE THREAD

**Issue by dim895** [jeromebq/PCF_AddressAPI#12]
Hello Jérôme,

It's me again :(. I added the PCF twice and have some bugs that I am not able to reproduce every time which makes it difficult to explain.

What happens quite often:

- When i fill the second, sometimes it deletes also the first
- Sometimes it gets stuck and fields are not filled in
- Sometimes it works great!:)

I uploaded a video where you can see the bug.

From 1 sec to 16 second: Everything works fine, then secondary address is deleted and then again it works fine.

I am unable to explain why this happens.

Please let me know if I can be of any assistance.
Je peux également switcher en Français si besoin!

Le lien de la vidéo est ici si besoin:
https://we.tl/t-29Ws3ia9MN

Thanks in advance,

Dimitri

**Comment by jeromebq** [comment]
Hello,

Thanks, I'm working on a fix.

Thanks for the video

Jerome

**Comment by jeromebq** [comment]
Hello,

I fixed the bug, I hope i covered all cases.
The solution version is number 3.1.0.0 now.

Jerome

**Comment by dim895** [comment]
Hello, Thank you so much. I will check it tomorrow and let you know. 

Dimitri

**Comment by dim895** [comment]
Hi Jérôme;

As expected I tested today with the new version, it is much more stable and thank you for that.  

However, I am still facing some issues where my selection is for example not splitted in the fields and save is not taken into account.

I do have a business rule that hides the control, do you think thant it could such an error?

I have added a video in which you can see that there are two problems (probably linked).

1) Search is not split up
2) I do save but then everything is deleted
3) once I refresh and do the same, everything works fine

URL of the video : https://we.tl/t-IYZVMqAdrN

Let me know if I can be of any assistance.

Best regards,

Dimitri

**Comment by jeromebq** [comment]
Hi,

I had this issue before, but normally on my new version it's fixed. 

Please make sure you have the lastest solution version 3.1.0.0, from the folder "AddressAPI_Solution"

Thanks,

Jerome

**Comment by dim895** [comment]
Hello,

OK I will check it again tonight and let you know ASAP.

**Comment by dim895** [comment]
Hi Jérôme,

I indeed deleted the solution and imported the latest solution to make sure. Looks perfect.

I have given it for further testing and let you know if we ever have similar issues.

I would like to thank you for all the hard work you've done.

Best regards,

Dimitri
